apiVersion: v1
kind: Pod
metadata:
  name: gpu-test
  namespace: llm-testing
spec:
  containers:
  - name: gpu-test
    image: nvidia/cuda:11.8-runtime-ubuntu20.04
    command: ["sleep", "3600"]
    resources:
      limits:
        nvidia.com/gpu: 1
      requests:
        nvidia.com/gpu: 1
  nodeSelector:
    eks-node: gpu
  restartPolicy: Never
