#!/bin/bash

echo "=== GPU Time-Slicing Performance Testing Guide ==="
echo ""
echo "STEP 1: Test Phi-3.5 Individual Performance"
echo "Run: kubectl scale deployment deepseek-r1-baseline --replicas=0 -n llm-testing"
echo "Wait 30 seconds, then run: ./load_test.sh"
echo ""
echo "STEP 2: Test DeepSeek Individual Performance" 
echo "Run: kubectl scale deployment mistral-7b-baseline --replicas=0 -n llm-testing"
echo "Run: kubectl scale deployment deepseek-r1-baseline --replicas=1 -n llm-testing"
echo "Wait 30 seconds, then run: ./load_test.sh"
echo ""
echo "STEP 3: Test Both Models Concurrent Performance"
echo "Run: kubectl scale deployment mistral-7b-baseline --replicas=1 -n llm-testing"
echo "Wait 30 seconds, then run: ./load_test.sh"
echo ""
echo "The script will automatically detect which models are active and run appropriate tests."
echo "Final analysis will show performance impact percentages."
